### ISSUE TITLE
AttributeError: 'module' object has no attribute 'QR_DIR'

### ISSUE THREAD

**Issue by hillerliao** [littlecodersh/EasierLife#1]
''''
Traceback (most recent call last):
  File "QRCode.py", line 5, in <module>
    QR_DIR = config.QR_DIR
AttributeError: 'module' object has no attribute 'QR_DIR'
'''

**Comment by littlecodersh** [comment]
@hillerliao 你好，
已经修复了这一问题，重新下载即可。
感谢你的反馈。
