### ISSUE TITLE
Can you provide a new version ruuning on python3

### ISSUE THREAD

**Issue by tylor-e** [littlecodersh/EasierLife#2]
我想找一个能在command line显示二维码的，我看到你有QRCODE这个plugin，但是是py2.7的，能否支持py3呢？

**Comment by littlecodersh** [comment]
@tylor-e which program do you need?

**Comment by tylor-e** [comment]
看起来是可以说中文的。。。我想找一个能在command line显示二维码的，我看到你有QRCODE这个plugin，但是是py2.7的，能否支持py3呢？

**Comment by tylor-e** [comment]
@littlecodersh 原来itChat也是你的大作。。。 我就是在学习你的itChat看到了这个
之前用Urinx的版本BUG比较多，你这个跟适合我二次开发，在寻找远程服务器后台运行的解决方案，第一个问题就是要解决扫描二维码，看到你推荐的这个，觉得是好方法

**Comment by littlecodersh** [comment]
@tylor-e 我这里测试下来py3是直接可以用的，可以提供一下你那里的报错吗？

**Comment by tylor-e** [comment]
@littlecodersh 我这里提示没有PIL模块，看来直接装一个接行了？我看了要求2.7以为不能在py3.5用，再试试

**Comment by littlecodersh** [comment]
@tylor-e `pip install pillow`就可以了

**Comment by tylor-e** [comment]
@littlecodersh 好的，谢谢

**Comment by tylor-e** [comment]
我在阿里云服务器上装pillow报错

``` bash
ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7vo7jd5i/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-7a4r17q5-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-7vo7jd5i/pillow/
```

请问是还需要什么么？我pip install Image也报错 @littlecodersh

**Comment by littlecodersh** [comment]
@tylor-e python版本具体是多少？

**Comment by tylor-e** [comment]
@littlecodersh 3.4.3

**Comment by littlecodersh** [comment]
@tylor-e linux哪个版本？

**Comment by tylor-e** [comment]
CentOS 6.5 x64 @littlecodersh

**Comment by littlecodersh** [comment]
@tylor-e 试试这个命令：

``` bash
yum install libjpeg-turbo-devel
```

**Comment by tylor-e** [comment]
yum 报错，然后我搜了一篇帖子重装yum的，结果卸载完下好安装包提示我缺少依赖python2.4 .... @littlecodersh

**Comment by littlecodersh** [comment]
@tylor-e 应该是缺少`libjpeg`这个组件，具体情况有很多可能，我这里给建议的话效率也不高，你尝试通过搜索引擎安装一下吧
